.\" Copyright (C) 1999-2000 Cameron Moore
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
.\" Or try here: http://www.fsf.org/copyleft/gpl.html
.\"
.TH away 1 "October 2000" Linux "User Manuals"
.SH NAME
away \- terminal locking program
.SH SYNOPSIS
.B away [OPTIONS]
.I message
.B [...]
.SH DESCRIPTION
.B away
is a simple program that locks your terminal, checks for new mail
in any given number of mailboxes, and lets other users know why
you are inactive.
.SH OPTIONS
.IP "-c, --conf=FILE"
Specify an alternative configuration file instead of the default
~/.awayrc file.
.IP "-h, --help"
Display help.
.IP "-m, --message"
Execute as the remainder of the command line, effectively stripping
off the executable name and additional switches.
.IP "-p, --persist"
Continue checking for new mail as long as there is at least one mailbox
that has not received new mail.
.IP "-P, --nopersist"
Stop checking mail if any mailbox is found to have new mail.
.IP "-w, --wait=SECS"
Set how long, in seconds, the program waits between mail checks.
.IP "-W, --nowait"
Ignore any changes to the wait time and use the default time period.
.IP "-v, --version"
Display version information.
.SH FILES
.I ~/.awayrc
.RS
Per user configuration file. See
.BR awayrc (5)
for further details.
.RE

.I /etc/pam.d/away
.RS
The
.B Linux-PAM
configuration file.
.RE
.SH SEE ALSO
.BR awayrc (5)
.SH AUTHORS
Cameron Moore <cameron@unbeatenpath.net>, and others.
